version: "3.9"

services:
  spark-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-notebook
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./data:/workspace/data
    environment:
      - PYSPARK_PYTHON=python
      - PYSPARK_DRIVER_PYTHON=python
    depends_on:
      warehouse:
        condition: service_healthy

  warehouse:
    image: postgres:13
    container_name: warehouse
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=source
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d source"]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 5s

  warehouseui:
    image: dpage/pgadmin4
    container_name: warehouseui
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - db-ui-data:/var/lib/pgadmin
    ports:
      - "8085:80"
    depends_on:
      warehouse:
        condition: service_started

  ingest-data:
    build: .
    container_name: ingest-data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=warehouse
      - POSTGRES_PORT=5432
      - POSTGRES_DB=source
      - DATA_PATH=/workspace/data/users.csv
      - TABLE_NAME=users
    volumes:
      - ./data:/workspace/data
    depends_on:
      warehouse:
        condition: service_healthy

  scheduler:
    image: mageai/mageai
    container_name: scheduler
    volumes:
      - scheduler-data:/home/src
    ports:
      - "6789:6789"
    command: /app/run_app.sh mage start scheduler
    depends_on:
      warehouse:
        condition: service_healthy

volumes:
  db-data:
  db-ui-data:
  scheduler-data:
